// packages/react/src/typed-charts.tsx
import type {
  Disease,
  UF,
  Theme,
  Language,
  ChartParams,
  EpiscannerMetric,
} from "@mosqlimate/charts";
import { MosqlimateChart } from "./chart";

export interface RtChartProps {
  disease: Disease;
  geocode: number;
  start?: string;
  end?: string;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function RtChart({
  disease,
  geocode,
  start,
  end,
  ...rest
}: RtChartProps) {
  return (
    <MosqlimateChart
      chart="infodengue/rt"
      params={{ disease, geocode, start, end } as ChartParams}
      {...rest}
    />
  );
}

export interface TemperatureChartProps {
  geocode: number;
  start?: string;
  end?: string;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function TemperatureChart({
  geocode,
  start,
  end,
  ...rest
}: TemperatureChartProps) {
  return (
    <MosqlimateChart
      chart="climate/temperature"
      params={{ geocode, start, end } as ChartParams}
      {...rest}
    />
  );
}

export interface AccumulatedWaterfallChartProps {
  geocode: number;
  start?: string;
  end?: string;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function AccumulatedWaterfallChart({
  geocode,
  start,
  end,
  ...rest
}: AccumulatedWaterfallChartProps) {
  return (
    <MosqlimateChart
      chart="climate/accumulated-waterfall"
      params={{ geocode, start, end } as ChartParams}
      {...rest}
    />
  );
}

export interface AirChartProps {
  geocode: number;
  start?: string;
  end?: string;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function AirChart({ geocode, start, end, ...rest }: AirChartProps) {
  return (
    <MosqlimateChart
      chart="climate/umid-pressao-med"
      params={{ geocode, start, end } as ChartParams}
      {...rest}
    />
  );
}

export interface EggsDensityChartProps {
  start?: string;
  end?: string;
  uf?: UF;
  geocode?: number;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function EggsDensityChart({
  start,
  end,
  uf,
  geocode,
  ...rest
}: EggsDensityChartProps) {
  return (
    <MosqlimateChart
      chart="contaovos/eggs_density"
      params={{ start, end, uf, geocode } as ChartParams}
      {...rest}
    />
  );
}

export interface PositivityChartProps {
  start?: string;
  end?: string;
  uf?: UF;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function PositivityChart({
  start,
  end,
  uf,
  ...rest
}: PositivityChartProps) {
  return (
    <MosqlimateChart
      chart="contaovos/positivity"
      params={{ start, end, uf } as ChartParams}
      {...rest}
    />
  );
}

export interface MapChartProps {
  start?: string;
  end?: string;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function MapChart({ start, end, ...rest }: MapChartProps) {
  return (
    <MosqlimateChart
      chart="contaovos/map"
      params={{ start, end } as ChartParams}
      {...rest}
    />
  );
}

export interface ScatterChartProps {
  start?: string;
  end?: string;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function ScatterChart({ start, end, ...rest }: ScatterChartProps) {
  return (
    <MosqlimateChart
      chart="contaovos/map/scatter"
      params={{ start, end } as ChartParams}
      {...rest}
    />
  );
}

export interface EpiscannerChartProps {
  disease: Disease;
  uf: UF;
  year: number;
  metric?: EpiscannerMetric;
  theme?: Theme;
  language?: Language;
  width?: number;
  height?: number;
}
export function EpiscannerChart({
  disease,
  uf,
  year,
  metric,
  ...rest
}: EpiscannerChartProps) {
  return (
    <MosqlimateChart
      chart="episcanner"
      params={{ disease, uf, year, metric } as ChartParams}
      {...rest}
    />
  );
}

// packages/angular/src/typed-charts.ts
import { Component, Directive, Input, type OnChanges } from "@angular/core";
import type {
  ChartParams,
  Disease,
  EpiscannerMetric,
  Language,
  Theme,
  UF,
} from "@mosqlimate/charts";
import { MosqlimateChartComponent } from "./chart.component";

@Directive()
export abstract class MosqlimateTypedChartComponent implements OnChanges {
  @Input() theme?: Theme;
  @Input() language?: Language;
  @Input() width?: number;
  @Input() height?: number;

  protected cachedParams?: ChartParams;

  ngOnChanges(): void {
    this.cachedParams = undefined;
  }

  protected get params(): ChartParams {
    if (!this.cachedParams) {
      this.cachedParams = this.buildParams();
    }
    return this.cachedParams;
  }

  protected abstract buildParams(): ChartParams;
}

@Component({
  selector: "ngx-mosqlimate-rt-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'infodengue/rt'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class RtChartComponent extends MosqlimateTypedChartComponent {
  @Input() disease!: Disease;
  @Input() geocode!: number;
  @Input() start?: string;
  @Input() end?: string;

  protected override buildParams(): ChartParams {
    return {
      disease: this.disease,
      geocode: this.geocode,
      start: this.start,
      end: this.end,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-temperature-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'climate/temperature'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class TemperatureChartComponent extends MosqlimateTypedChartComponent {
  @Input() geocode!: number;
  @Input() start?: string;
  @Input() end?: string;

  protected override buildParams(): ChartParams {
    return {
      geocode: this.geocode,
      start: this.start,
      end: this.end,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-accumulated-waterfall-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'climate/accumulated-waterfall'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class AccumulatedWaterfallChartComponent extends MosqlimateTypedChartComponent {
  @Input() geocode!: number;
  @Input() start?: string;
  @Input() end?: string;

  protected override buildParams(): ChartParams {
    return {
      geocode: this.geocode,
      start: this.start,
      end: this.end,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-air-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'climate/umid-pressao-med'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class AirChartComponent extends MosqlimateTypedChartComponent {
  @Input() geocode!: number;
  @Input() start?: string;
  @Input() end?: string;

  protected override buildParams(): ChartParams {
    return {
      geocode: this.geocode,
      start: this.start,
      end: this.end,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-eggs-density-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'contaovos/eggs_density'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class EggsDensityChartComponent extends MosqlimateTypedChartComponent {
  @Input() start?: string;
  @Input() end?: string;
  @Input() uf?: UF;
  @Input() geocode?: number;

  protected override buildParams(): ChartParams {
    return {
      start: this.start,
      end: this.end,
      uf: this.uf,
      geocode: this.geocode,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-positivity-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'contaovos/positivity'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class PositivityChartComponent extends MosqlimateTypedChartComponent {
  @Input() start?: string;
  @Input() end?: string;
  @Input() uf?: UF;

  protected override buildParams(): ChartParams {
    return {
      start: this.start,
      end: this.end,
      uf: this.uf,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-map-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'contaovos/map'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class MapChartComponent extends MosqlimateTypedChartComponent {
  @Input() start?: string;
  @Input() end?: string;

  protected override buildParams(): ChartParams {
    return {
      start: this.start,
      end: this.end,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-scatter-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'contaovos/map/scatter'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class ScatterChartComponent extends MosqlimateTypedChartComponent {
  @Input() start?: string;
  @Input() end?: string;

  protected override buildParams(): ChartParams {
    return {
      start: this.start,
      end: this.end,
    } as ChartParams;
  }
}

@Component({
  selector: "ngx-mosqlimate-episcanner-chart",
  standalone: true,
  imports: [MosqlimateChartComponent],
  template: `
    <ngx-mosqlimate-chart
      [chart]="'episcanner'"
      [params]="params"
      [theme]="theme"
      [language]="language"
      [width]="width"
      [height]="height"
    ></ngx-mosqlimate-chart>
  `,
})
export class EpiscannerChartComponent extends MosqlimateTypedChartComponent {
  @Input() disease!: Disease;
  @Input() uf!: UF;
  @Input() year!: number;
  @Input() metric?: EpiscannerMetric;

  protected override buildParams(): ChartParams {
    return {
      disease: this.disease,
      uf: this.uf,
      year: this.year,
      metric: this.metric,
    } as ChartParams;
  }
}
