// packages/react/src/context.tsx
import { createContext, useContext, useEffect, type ReactNode } from "react";
import type { Language, Theme } from "@mosqlimate/charts";

interface MosqlimateContextValue {
  api_key?: string;
  sdk_key?: string;
  theme?: Theme;
  language?: Language;
}

const MosqlimateContext = createContext<MosqlimateContextValue | null>(null);

export interface MosqlimateProviderProps {
  api_key?: string;
  sdk_key?: string;
  theme?: Theme;
  language?: Language;
  children: ReactNode;
}

export function MosqlimateProvider({
  api_key,
  sdk_key,
  theme,
  language,
  children,
}: MosqlimateProviderProps) {
  useEffect(() => {
    (async () => {
      const { Mosqlimate } = await import("@mosqlimate/charts");
      if (sdk_key) Mosqlimate.setSdkKey(sdk_key);
      if (api_key) Mosqlimate.setApiKey(api_key);
      if (theme || language)
        Mosqlimate.configure({
          ...(theme && { theme }),
          ...(language && { language }),
        });
    })();
  }, [api_key, sdk_key, theme, language]);

  return (
    <MosqlimateContext.Provider value={{ api_key, sdk_key, theme, language }}>
      {children}
    </MosqlimateContext.Provider>
  );
}

export function useMosqlimate(): MosqlimateContextValue {
  const ctx = useContext(MosqlimateContext);
  return ctx ?? {};
}

// packages/svelte/src/lib/context.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { Language, Theme } from "@mosqlimate/charts";
  import { provideMosqlimate } from "./context";
  import type { MosqlimateContextValue } from "./types";

  interface Props {
    api_key?: string;
    sdk_key?: string;
    theme?: Theme;
    language?: Language;
    children?: Snippet;
  }

  let { api_key, sdk_key, theme, language, children }: Props = $props();

  let ctx = $state<MosqlimateContextValue>({});
  provideMosqlimate(ctx);

  $effect(() => {
    ctx.api_key = api_key;
    ctx.sdk_key = sdk_key;
    ctx.theme = theme;
    ctx.language = language;
  });

  $effect(() => {
    void api_key;
    void sdk_key;
    void theme;
    void language;
    (async () => {
      const { Mosqlimate } = await import("@mosqlimate/charts");
      if (sdk_key) Mosqlimate.setSdkKey(sdk_key);
      if (api_key) Mosqlimate.setApiKey(api_key);
      if (theme || language)
        Mosqlimate.configure({
          ...(theme ? { theme } : {}),
          ...(language ? { language } : {}),
        });
    })();
  });
</script>

{@render children?.()}
